import enum


class PAY_ORGANIZATION(enum.IntEnum):
    NONE = 0
    VISA = 10
    MASTERCARD = 20
    JCB = 30

PAY_ORGANIZATION_CHOICES = [
    (PAY_ORGANIZATION.VISA, ('VISA')),
    (PAY_ORGANIZATION.MASTERCARD, ('MASTERCARD')),
    (PAY_ORGANIZATION.JCB, ('JCB'))
]


class PAYMENT_STATUS(enum.IntEnum):
    NONE = 0
    FAILED = 10
    PAID = 20

PAYMENTSTATUS_CHOICES = [
    (PAYMENT_STATUS.NONE, ('NONE')),
    (PAYMENT_STATUS.FAILED, ('FAILED')),
    (PAYMENT_STATUS.PAID, ('PAID'))
]


class ORDER_STATUS(enum.IntEnum):
    NON_SUBMIT = 0
    SUBMIT = 10
    ERROR = 20
    CANCEL = 30

ORDERSTATUS_CHOICES = [
    (ORDER_STATUS.NON_SUBMIT ,('NON_SUBMIT')),
    (ORDER_STATUS.SUBMIT, ('SUBMIT')),
    (ORDER_STATUS.ERROR, ('ERROR')),
    (ORDER_STATUS.CANCEL, ('CANCEL'))
    ]