# Generated by Django 4.0.4 on 2022-08-07 07:41

import asns.commons
import base.commons
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ASNHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date_time', models.DateTimeField(auto_now_add=True, db_column='CREATE_DATE_TIME', db_index=True, verbose_name='Create Date Time')),
                ('last_update_date_time', models.DateTimeField(auto_now=True, db_column='LAST_UPDATE_DATE_TIME', db_index=True, verbose_name='Last Update Date Time')),
                ('is_return', models.BooleanField(default=False, verbose_name='Return')),
                ('received', models.BooleanField(default=False, verbose_name='Received')),
                ('receiver_name', models.CharField(max_length=50, null=True, verbose_name='Receiver Name')),
                ('receiver_phone', models.CharField(max_length=10, null=True, verbose_name='Receiver Phone Number')),
                ('shipping_address', models.CharField(max_length=200, null=True, verbose_name='Shipping Address')),
                ('city', models.CharField(max_length=20, null=True, verbose_name='City')),
                ('post_code', models.CharField(max_length=6, null=True, verbose_name='Post Code')),
                ('asn_serial_number', models.CharField(max_length=100, null=True, unique=True, verbose_name='Shipment Serial Number')),
                ('error_message', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Error Message')),
                ('asn_status', models.PositiveSmallIntegerField(choices=[(asns.commons.ASN_STATUS['NEW'], 'NEW'), (asns.commons.ASN_STATUS['NEW'], 'PROCESSING'), (asns.commons.ASN_STATUS['READY_TO_DELIVERY'], 'READY_TO_DELIVERY'), (asns.commons.ASN_STATUS['DELIVERYING'], 'DELIVERYING'), (asns.commons.ASN_STATUS['SENT'], 'SENT'), (asns.commons.ASN_STATUS['CANCEL'], 'CANCEL'), (asns.commons.ASN_STATUS['ASN_ERROR'], 'ASN_ERROR'), (asns.commons.ASN_STATUS['FAILED_DELIVERY'], 'FAILED_DELIVERY')], db_index=True, default=asns.commons.ASN_STATUS['NEW'], verbose_name='ASN Status')),
                ('delivery_by', models.PositiveSmallIntegerField(choices=[(base.commons.DELIVERY_BY['NONE'], 'NONE'), (base.commons.DELIVERY_BY['CON_SEVEN'], 'CON_SEVEN'), (base.commons.DELIVERY_BY['CON_FAMILY'], 'CON_FAMILY'), (base.commons.DELIVERY_BY['CON_HILIFE'], 'CON_HILIFE'), (base.commons.DELIVERY_BY['CON_OK'], 'CON_OK'), (base.commons.DELIVERY_BY['DE_POST'], 'DE_POST'), (base.commons.DELIVERY_BY['DE_BLACKCAT'], 'DE_BLACKCAT'), (base.commons.DELIVERY_BY['DE_OTHERS'], 'DE_OTHERS')], db_index=True, default=base.commons.DELIVERY_BY['NONE'], verbose_name='Delivery By')),
                ('feedback', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Custom Feedback')),
                ('reply', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Feedback Reply')),
            ],
            options={
                'verbose_name': 'ASN Header',
                'verbose_name_plural': 'ASN Header',
            },
        ),
        migrations.CreateModel(
            name='ASNLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date_time', models.DateTimeField(auto_now_add=True, db_column='CREATE_DATE_TIME', db_index=True, verbose_name='Create Date Time')),
                ('last_update_date_time', models.DateTimeField(auto_now=True, db_column='LAST_UPDATE_DATE_TIME', db_index=True, verbose_name='Last Update Date Time')),
                ('is_return', models.BooleanField(default=False, verbose_name='Return')),
                ('received', models.BooleanField(default=False, verbose_name='Received')),
                ('asn_line_no', models.PositiveSmallIntegerField(default=1, verbose_name='ASNLine Line Number')),
                ('quantity', models.IntegerField(null=True, verbose_name='Quantity')),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asns.asnheader', verbose_name='ASN Header')),
            ],
            options={
                'verbose_name': 'ASN Line',
                'verbose_name_plural': 'ASN Line',
            },
        ),
    ]
