# Generated by Django 4.0.4 on 2022-08-07 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('orders', '0001_initial'),
        ('asns', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asnline',
            name='order_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orderline', verbose_name='Order Line'),
        ),
        migrations.AddField(
            model_name='asnline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='asnheader',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='asnheader',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member', verbose_name='User'),
        ),
        migrations.AlterUniqueTogether(
            name='asnline',
            unique_together={('header', 'asn_line_no')},
        ),
    ]
