import enum


class ASN_STATUS(enum.IntEnum):
    NEW = 10
    PROCESSING = 10
    READY_TO_DELIVERY = 20
    DELIVERYING = 30
    SENT = 40
    CANCEL = 50
    ASN_ERROR = 60
    FAILED_DELIVERY = 70

ASN_STATUS_CHOICES = [
    (ASN_STATUS.NEW, ('NEW')),
    (ASN_STATUS.PROCESSING, ('PROCESSING')),
    (ASN_STATUS.READY_TO_DELIVERY, ('READY_TO_DELIVERY')),
    (ASN_STATUS.DELIVERYING, ('DELIVERYING')),
    (ASN_STATUS.SENT, ('SENT')),
    (ASN_STATUS.CANCEL, ('CANCEL')),
    (ASN_STATUS.ASN_ERROR, ('ASN_ERROR')),
    (ASN_STATUS.FAILED_DELIVERY, ('FAILED_DELIVERY'))
    ]