import enum

class DELIVERY_BY(enum.IntEnum):
    NONE = 0
    CON_SEVEN = 10
    CON_FAMILY = 20
    CON_HILIFE = 30
    CON_OK = 40
    DE_POST = 50
    DE_BLACKCAT = 60
    DE_OTHERS = 70

DELIVERY_BY_CHOICES = [
    (DELIVERY_BY.NONE, ('NONE')),
    (DELIVERY_BY.CON_SEVEN, ('CON_SEVEN')),
    (DELIVERY_BY.CON_FAMILY, ('CON_FAMILY')),
    (DELIVERY_BY.CON_HILIFE, ('CON_HILIFE')),
    (DELIVERY_BY.CON_OK, ('CON_OK')),
    (DELIVERY_BY.DE_POST, ('DE_POST')),
    (DELIVERY_BY.DE_BLACKCAT, ('DE_BLACKCAT')),
    (DELIVERY_BY.DE_OTHERS, ('DE_OTHERS'))
    ]