# Generated by Django 4.0.4 on 2022-08-07 07:41

import base.commons
from django.db import migrations, models
import django.db.models.deletion
import orders.commons


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date_time', models.DateTimeField(auto_now_add=True, db_column='CREATE_DATE_TIME', db_index=True, verbose_name='Create Date Time')),
                ('last_update_date_time', models.DateTimeField(auto_now=True, db_column='LAST_UPDATE_DATE_TIME', db_index=True, verbose_name='Last Update Date Time')),
                ('cancel', models.BooleanField(default=False, verbose_name='Cancel')),
                ('order_serial_number', models.CharField(max_length=200, null=True, unique=True, verbose_name='Order Serial Number')),
                ('receiver_name', models.CharField(max_length=50, null=True, verbose_name='Receiver Name')),
                ('receiver_phone', models.CharField(max_length=10, null=True, verbose_name='Receiver Phone Number')),
                ('shipping_address', models.CharField(max_length=200, null=True, verbose_name='Shipping Address')),
                ('city', models.CharField(max_length=20, null=True, verbose_name='City')),
                ('post_code', models.CharField(max_length=6, null=True, verbose_name='Post Code')),
                ('total_price', models.PositiveIntegerField(null=True, verbose_name='Toatal Price')),
                ('comment', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Custom Comment')),
                ('order_status', models.PositiveSmallIntegerField(choices=[(orders.commons.ORDER_STATUS['NON_SUBMIT'], 'NON_SUBMIT'), (orders.commons.ORDER_STATUS['SUBMIT'], 'SUBMIT'), (orders.commons.ORDER_STATUS['ERROR'], 'ERROR'), (orders.commons.ORDER_STATUS['CANCEL'], 'CANCEL')], db_index=True, default=orders.commons.ORDER_STATUS['NON_SUBMIT'], verbose_name='Order Status')),
                ('delivery_by', models.PositiveSmallIntegerField(choices=[(base.commons.DELIVERY_BY['NONE'], 'NONE'), (base.commons.DELIVERY_BY['CON_SEVEN'], 'CON_SEVEN'), (base.commons.DELIVERY_BY['CON_FAMILY'], 'CON_FAMILY'), (base.commons.DELIVERY_BY['CON_HILIFE'], 'CON_HILIFE'), (base.commons.DELIVERY_BY['CON_OK'], 'CON_OK'), (base.commons.DELIVERY_BY['DE_POST'], 'DE_POST'), (base.commons.DELIVERY_BY['DE_BLACKCAT'], 'DE_BLACKCAT'), (base.commons.DELIVERY_BY['DE_OTHERS'], 'DE_OTHERS')], db_index=True, default=base.commons.DELIVERY_BY['NONE'], verbose_name='Delivery By')),
                ('failed_asn', models.BooleanField(default=False, verbose_name='ASN Failed ?')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Is checkout ?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Order Header',
                'verbose_name_plural': 'Order Header',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date_time', models.DateTimeField(auto_now_add=True, db_column='CREATE_DATE_TIME', db_index=True, verbose_name='Create Date Time')),
                ('last_update_date_time', models.DateTimeField(auto_now=True, db_column='LAST_UPDATE_DATE_TIME', db_index=True, verbose_name='Last Update Date Time')),
                ('pay_org', models.PositiveSmallIntegerField(choices=[(orders.commons.PAY_ORGANIZATION['VISA'], 'VISA'), (orders.commons.PAY_ORGANIZATION['MASTERCARD'], 'MASTERCARD'), (orders.commons.PAY_ORGANIZATION['JCB'], 'JCB')], db_index=True, default=orders.commons.PAY_ORGANIZATION['NONE'], verbose_name='Payment Organization')),
                ('card_last_number', models.CharField(max_length=4, null=True, verbose_name='Credit Card last four number')),
                ('payment_status', models.PositiveSmallIntegerField(choices=[(orders.commons.PAYMENT_STATUS['NONE'], 'NONE'), (orders.commons.PAYMENT_STATUS['FAILED'], 'FAILED'), (orders.commons.PAYMENT_STATUS['PAID'], 'PAID')], db_index=True, default=orders.commons.PAYMENT_STATUS['NONE'], verbose_name='Payment Status')),
                ('total_price', models.PositiveIntegerField(null=True, verbose_name='Toatal Price')),
                ('order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payment',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True, verbose_name='Quantity')),
                ('has_order', models.BooleanField(default=False, verbose_name='Has Order ?')),
                ('is_checkout', models.BooleanField(default=False, verbose_name='Is checkout ?')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Order')),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.payment', verbose_name='Payment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Cart',
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveIntegerField(default=1, null=True, verbose_name='Line Number')),
                ('quantity', models.IntegerField(null=True, verbose_name='Quantity')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Order Header')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Order Line',
                'verbose_name_plural': 'Order Line',
                'unique_together': {('order', 'line_no')},
            },
        ),
    ]
