# Generated by Django 4.0.4 on 2022-08-07 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(db_index=True, max_length=128, null=True, verbose_name='Brand Name')),
                ('tax_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tax Number')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('contactor', models.CharField(blank=True, max_length=20, null=True, verbose_name='Contactor')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Address')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Brand')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brand',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('create_date_time', models.DateTimeField(auto_now_add=True, db_column='CREATE_DATE_TIME', db_index=True, verbose_name='Create Date Time')),
                ('last_update_date_time', models.DateTimeField(auto_now=True, db_column='LAST_UPDATE_DATE_TIME', db_index=True, verbose_name='Last Update Date Time')),
                ('product_type_name', models.CharField(db_column='TYPE_NAME', db_index=True, default=None, max_length=128, verbose_name='Prodcut Type Name')),
                ('is_available', models.BooleanField(db_column='IS_AVAILABLE', db_index=True, default=True, verbose_name='Is Available')),
                ('product_code', models.AutoField(default='Typingshop00001', primary_key=True, serialize=False, verbose_name='Prodcut Code')),
                ('product_name', models.CharField(db_index=True, max_length=128, null=True, verbose_name='Prodcut Type Name')),
                ('price', models.CharField(db_index=True, max_length=200, null=True, verbose_name='Price')),
                ('stock_quantity', models.CharField(db_index=True, default=0, max_length=1024, verbose_name='Stock Quantity')),
                ('unit', models.CharField(blank=True, help_text='For instance : Pices or a Package', max_length=100, null=True, verbose_name='Unit')),
                ('color', models.CharField(blank=True, max_length=20, null=True, verbose_name='Color')),
                ('manufactor', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Manufator')),
                ('manufactor_address', models.CharField(blank=True, max_length=300, null=True, verbose_name='Manufactor Address')),
                ('non_returnable', models.BooleanField(default=False, verbose_name='Non Returnable')),
                ('out_of_stock', models.BooleanField(default=False, help_text='If it is True, then set stock quantity as zero', verbose_name='Out of Stock')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.brand', verbose_name='Brand')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Product',
            },
        ),
    ]
